version: "3.7"
services:
  fish:
    restart: always
    build: .
    ports:
      - "80:80"
    networks:
      - fishnet
    environment:
      - TOKEN_API=
      - LOGIN_DB=seunome
      - SENHA_DB=suasenha
      - HOST_DB=mongodb:27017
      - CLUSTER_DB=admin
      - FORMAT_DB=mongodb
      - PORT=80
  mongodb:
    restart: always
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ~/apps/mongo:/data/db
    networks:
      - fishnet
    environment:
      - MONGO_INITDB_ROOT_USERNAME=seunome
      - MONGO_INITDB_ROOT_PASSWORD=suasenha
networks:
  fishnet:
    driver: bridge
